### ISSUE TITLE
Add support for installing Neovim

### ISSUE THREAD

**Issue by blueyed** [tweekmonster/vim-testbed#1]
Might be as easy as the following for nightlies (works for Travis):

```
  eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
```

https://github.com/neovim/bot-ci/blob/master/scripts/travis-setup.sh
https://github.com/neovim/bot-ci#nightly-builds

Support for specific versions might me nice though, too - but not really required at the moment.

**Comment by tweekmonster** [comment]
Oh cool, that'll be useful.  This was something I wanted to look into doing.

**Comment by blueyed** [comment]
Can you provide some input of how it should be done?
Should there be a `install_nvim.sh` script?

**Comment by tweekmonster** [comment]
Sorry this fell off my todo list.  I haven't actually tried it yet, but it should just need to be installed in a place where `run_vim.sh` expects it.

> Should there be a install_nvim.sh script?

Yeah, I think that would keep it simple.  `XDG_` variables should probably be set as well.

My thoughts left off on trying to get it to actually build the release versions in addition to nightly, but it wasn't working without using pre-built packages for libvterm and libtermkey from the testing channel(?).

I was also thinking about removing the requirement of sourcing `/rtp.vim` and having a standard vimrc script that loads a known script name from the volume instead.

Paging @mhinz in case he made some breakthrough with building Neovim in Alpine docker.

**Comment by blueyed** [comment]
I've created https://github.com/tweekmonster/vim-testbed/issues/8 for the better-vimrc-rtp.vim-handling.

**Comment by w0rp** [comment]
I'm looking forward to this. Thank you for writing `vim-testbed`. It has been very useful for testing a Vim plugin I have been working on.
