### ISSUE TITLE
Move (Docker) repository to organisation?

### ISSUE THREAD

**Issue by blueyed** [tweekmonster/vim-testbed#14]
I'd like to be able to push new base images myself, and therefore think it makes sense to move this repo to an org and/or provide access to the Docker repository (https://hub.docker.com/r/tweekmonster/vim-testbed/) to me.

**Comment by tweekmonster** [comment]
Yeah I think that would be a good idea.  I'm out of town for the rest of the weekend, so I'm just going to give you access to the Docker repo in the mean time.

**Comment by tweekmonster** [comment]
@blueyed I was surprisingly able to create the organization "testbed", so we could have `testbed/vim` and other kinds of test containers if we ever get creative 😁

https://hub.docker.com/u/testbed/

**Comment by tweekmonster** [comment]
And thanks a lot for all the work you put in to this repo!  Sorry I wasn't around during all your activity.

**Comment by blueyed** [comment]
btw: https://github.com/testbed/ is taken, but looks interesting.. ;)

**Comment by blueyed** [comment]
I cannot push to https://hub.docker.com/r/testbed/vim/.  My Docker Hub username is "blueyed".

**Comment by blueyed** [comment]
When you're at it, please also add an user for automatic pushes (https://github.com/tweekmonster/vim-testbed/issues/19).  We would encrypt its auth in a secret for Travis then.

**Comment by tweekmonster** [comment]
@blueyed I added you to a group and forgot to add that group to the repo.  I just made you an owner in the org.  I'm a little confused by Docker Hub's ACLs.

Hopefully you'll have free reign on it and can add repositories.

**Comment by blueyed** [comment]
Yay, pushed to https://hub.docker.com/r/testbed/vim/.
Thanks!

**Comment by blueyed** [comment]
Closing this, thanks!

For the future:

> add an user for automatic pushes (#19)?! We would encrypt its auth in a secret for Travis then.

**Comment by tweekmonster** [comment]
@blueyed It just came to mind to look at this again.  It seems that `testbed` is available as an org.  I took it and invited you 🎉
