### ISSUE TITLE
Transfer to Vimjas org

### ISSUE THREAD

**Issue by blueyed** [tweekmonster/vim-testbed#72]
@tweekmonster 
Can we move this repo to https://github.com/Vimjas/ ?
I've noticed that I cannot change settings here, and then thought it would be good to have on an org anyway.

**Comment by tweekmonster** [comment]
@blueyed Yes that's fine.  Sorry for the delay!

**Comment by tweekmonster** [comment]
I got this error:

```
You don’t have the permission to create public repositories on Vimjas
```

**Comment by blueyed** [comment]
@tweekmonster I've invited you to the org, then it should work.

**Comment by blueyed** [comment]
Thanks!
