### ISSUE TITLE
Release updated docker image to DockerHub

### ISSUE THREAD

**Issue by hsanson** [tweekmonster/vim-testbed#89]
Would be appreciated if an updated image with #82 fix is released to Dockerhub:

 - https://hub.docker.com/r/testbed/vim/tags
 
 
 FYI: @blueyed

**Comment by blueyed** [comment]
Done, pushed tag 24 (sha256:e4aa605bc5aff03f2d3d20a1946c7d4a02f4af61b3f1c479697ac95dec97d0ed).
